cstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico',
         RedirectView.as_view(url='static/favicon.ico', permanent=False)),
    path('accounts/', include('allauth.urls')),
    path('', include('products.urls'), name='products'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from .views import (ProductDetailView, add_to_cart,
                    remove_from_cart, remove_single_item_from_cart,
                    IndexView, CollectionSearch, CartSummaryView,
                    CheckoutView, StripPaymentView, ProductList, 
                    FlutterwavePaymentView, AddCouponView, remove_coupon, show_category, CategoriesView)

app_name = 'products'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products/', ProductList.as_view(), name="products-list"),
    path('products/<slug:slug>/',
         ProductDetailView.as_view(),
         name="single-product"),
    path('summary/', CartSummaryView.as_view(), name="cart-summary"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-to-cart/<slug:slug>/', add_to_cart, name="add-to-cart"),
    path('add-coupon/', AddCouponView.as_view(), name="add-coupon"),
    path('remove-coupon/', remove_coupon, name="remove-coupon"),
    path('remove-from-cart/<slug:slug>/',
         remove_from_cart,
         name="remove-from-cart"),
    path('update-quantity-minus/<slug:slug>/',
         remove_single_item_from_cart,
         name="remove_single_item_from_cart"),
    path('update-quantity-plus/<slug:slug>/',
         add_to_cart,
         name="add_single_item_to_cart"),
    path('collections/<slug:slug>/', CollectionSearch.as_view(), name="collection"),
    path('categories/<slug:hierarchy>/', show_category, name="category"),
    path('categories/', CategoriesView.as_view(), name="categories"),
    path('payment/stripe/',
         StripPaymentView.as_view(),
         name="stripe"),
    path('payment/flutterwave/',
         FlutterwavePaymentView.as_view(),
         name="flutterwave"),

]

search/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class SearchTerm(models.Model):
    query = models.CharField(max_length=100)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.GenericIPAddressField()
    tracking_id = models.CharField(max_length=50, default='')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.query

products/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (('S', 'Stripe'), ('F', 'Flutterwave'))


class CheckoutForm(forms.Form):
    shipping_street_address = forms.CharField(required=False)
    shipping_apartment_address = forms.CharField(required=False)
    shipping_country = CountryField(
        blank_label='--- Select country ---').formfield(
            required=False,
            widget=CountrySelectWidget(attrs={'class': 'input'}))
    shipping_zip_code = forms.CharField(required=False)

    billing_street_address = forms.CharField(required=False)
    billing_apartment_address = forms.CharField(required=False)
    billing_country = CountryField(
        blank_label='--- Select country ---').formfield(
            required=False,
            widget=CountrySelectWidget(attrs={'class': 'input'}))
    billing_zip_code = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect,
                                       choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'style': 'background-color:#fff',
            'placeholder': 'Coupon code',
            'aria-label': 'Coupon code',
            'aria-describedby': 'button-addon1'
        }))


class ReviewForm(forms.Form):
    user_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder': 'Your Name'
        }))
    customer_email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder': 'Email Address'
        }))
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'input',
        'placeholder': 'Comment'
    }))
    rating = forms.IntegerField(max_value=5)

products/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView, DetailView
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from .models import Item, CartItem, Cart, Payment, Address, Coupon, Review, Order, Collection, Category
from search.models import SearchTerm
from .forms import CheckoutForm, CouponForm, ReviewForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import uuid
from stats import stats
from search.filter import ProductsSearch, SortForm
from django.db.models import Q

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


def show_category(request, hierarchy=None):
    category_slug = hierarchy.split('/')
    category_queryset = list(Category.objects.all())
    all_slugs = [x.slug for x in category_queryset]
    parent = None
    for slug in category_slug:
        if slug in all_slugs:
            parent = get_object_or_404(Category, slug=slug, parent=parent)
        else:
            instance = get_object_or_404(Item, slug=slug)
            breadcrumbs_link = instance.get_cat_list()
            category_name = [
                ' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link
            ]
            breadcrumbs = zip(breadcrumbs_link, category_name)
            return render(request, "products/product-page.html", {
                'instance': instance,
                'breadcrumbs': breadcrumbs
            })
        return render(
            request, "products/categories.html", {
                "item_set": parent.item_set.all(),
                'sub_categories': parent.children.all()
            })


class ProductList(View):
    def get(self, request, *args, **kwargs):
        sortForm = SortForm(request.GET or None)
        value = request.GET.get('query', '')
        sort_by = request.GET.get('sort_by', '')
        # store search query in the database
        if len(value) > 2:
            term = SearchTerm()
            term.query = value
            term.ip_address = request.META.get('REMOTE_ADDR')
            term.tracking_id = stats.tracking_id(request)
            term.user = None
            if request.user.is_authenticated:
                term.user = request.user
            term.save()
        products = ProductsSearch(request.GET or None,
                                  queryset=Item.objects.all())
        if sort_by:
            results_qs = products.qs.order_by(sort_by)
        else:
            results_qs = products.qs.order_by('price')
        print(request.get_full_path)
        paginator = Paginator(results_qs, 1)

        page = request.GET.get('page')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        context = {
            'object_list': products,
            'sortform': sortForm,
            'page': page,
            'results': results
        }
        return render(request, "products/products.html", context)


class CategoriesView(ListView):
    model = Category
    template_name = "products/all_categories_view.html"


class IndexView(View):
    def get(self, request, *args, **kwargs):
        search_recommendations = stats.recommended_from_search(self.request)
        latest = Item.objects.all()[:5]
        carousels = Collection.objects.carousels()[:5]
        collections = Collection.objects.collections()[:2]
        promos = Collection.objects.promos()[:10]
        recently_viewed = stats.get_recently_viewed(self.request)[:6]
        context = {
            "carousels": carousels,
            "collections": collections,
            "promos": promos,
            "latest": latest,
            "recently_viewed": recently_viewed,
            "search_recommendations": search_recommendations
        }
        return render(self.request, "products/index.html", context)


class CollectionSearch(View):
    def get(self, request, slug):
        collection = get_object_or_404(Collection, slug=slug)
        products = ProductsSearch(
            request.GET, queryset=collection.item_set.all())

        context = {"object_list": products}
        return render(self.request, "products/search-results.html", context)


class CartSummaryView(View):
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            try:
                cart = Cart.objects.get(user=self.request.user, ordered=False)

                context = {'object': cart, 'couponform': CouponForm()}
                return render(self.request, 'products/cart.html', context)
            except ObjectDoesNotExist:
                messages.warning(
                    self.request,
                    "Your cart is empty. Please add some items to your cart.")
                return redirect("/products")
        else:
            try:
                cart_id = self.request.session.get("cart_id")
                cart = Cart.objects.get(id=cart_id, ordered=False)

                context = {'object': cart}
                return render(self.request, 'products/cart.html', context)
            except ObjectDoesNotExist:
                messages.warning(
                    self.request,
                    "Your cart is empty. Please add some items to your cart.")
                return redirect("/products")


class ProductDetailView(View):
    def get(self, request, slug, *args, **kwargs):
        from stats import stats
        item = Item.objects.get(slug=slug)
        stats.log_item_view(self.request, item)
        form = ReviewForm()
        reviews = item.review_set.all()
        related_products = Item.objects.filter(
            Q(category=item.category)
            | Q(collections__in=item.collections.all())).distinct().exclude(
                slug=item.slug)
        paginator = Paginator(reviews, 1)

        page = request.GET.get('page')
        try:
            reviews = paginator.page(page)
        except PageNotAnInteger:
            reviews = paginator.page(1)
        except EmptyPage:
            reviews = paginator.page(paginator.num_pages)

        breadcrumbs_link = item.get_cat_list()
        category_name = [
            ' '.join(i.split('/')[-1].split('-')) for i in breadcrumbs_link
        ]
        breadcrumbs = zip(breadcrumbs_link, category_name)

        context = {
            'item': item,
            'object': item,
            'form': form,
            'reviews': reviews,
            'breadcrumbs': breadcrumbs,
            'related_products': related_products
        }
        return render(self.request, "products/product-page.html", context)

    def post(self, request, slug, *args, **kwargs):
        form = ReviewForm(self.request.POST or None)
        if form.is_valid():
            user_name = form.cleaned_data.get('user_name')
            customer_email = form.cleaned_data.get('customer_email')
            comment = form.cleaned_data.get('comment')
            rating = form.cleaned_data.get('rating')

            review = Review(item=get_object_or_404(Item, slug=slug),
                            user_name=user_name,
                            customer_email=customer_email,
                            comment=comment,
                            rating=rating,
                            created_at=timezone.now())

            review.save()
            messages.success(self.request, "Thanks for the feedback!!")
            return redirect("products:single-product", slug=slug)
        messages.warning(
            self.request,
            'Your feedback was not submitted, please fill the form and try again.'
        )
        return redirect('products:single-product', slug=slug)

        context = {'form': form}
        return render(self.request, "products/product-page.html", context)


class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        cart_qs = Cart.objects.filter(user=self.request.user, ordered=False)
        if cart_qs.exists():
            cart = cart_qs[0]
            order_qs = Order.objects.filter(user=self.request.user,
                                            items=cart,
                                            ordered=False)
            ordered_date = timezone.now()
            if order_qs.exists():
                order = order_qs[0]
                order.ordered_date = ordered_date
                order.save()
            else:
                order = Order.objects.create(user=self.request.user,
                                             items=cart,
                                             ordered=False,
                                             ordered_date=ordered_date)
                order.save()
        else:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/products")
        context = {'form': form}

        shipping_address_qs = Address.objects.filter(user=self.request.user,
                                                     address_type='S',
                                                     default_address=True)

        if shipping_address_qs.exists():
            context.update(
                {'default_shipping_address': shipping_address_qs[0]})

        billing_address_qs = Address.objects.filter(user=self.request.user,
                                                    address_type='B',
                                                    default_address=True)

        if billing_address_qs.exists():

search/views.py
from django.shortcuts import render

# Create your views here.

products/templates/products/includes/aside-filters.html
{% load static %}
{% load home_tags %}

<!-- ASIDE -->
<div id="aside" style="padding:20px" class="col-md-3">
{% if object_list %}
    <!-- aside widget -->
    {% comment %} <div class="aside">
        <h3 class="aside-title">Filter By Size:</h3>
        <ul class="size-option">
            <li class="active"><a href="#">S</a></li>
            <li class="active"><a href="#">XL</a></li>
            <li><a href="#">SL</a></li>
        </ul>
    </div> {% endcomment %}
    <!-- /aside widget -->
    <!-- aside widget -->
    <div class="aside">
        <h3 class="aside-title">Filter by Price:</h3>
        <div id="store-price-slider"></div>
        <div class="wrap">
            <div class="price_min_max">
                <div class="price_filter_min">
                    {{object_list.form.price_min}}
                </div>
                <span>-</span>
                <div class="price_filter_max">
                    {{object_list.form.price_max}}
                </div>   
            </div>
            <button class="primary-btn apply">Apply</button>
        </div>
    </div>
    <!-- aside widget -->
    <!-- aside widget -->
    <div class="aside">
        <h3 class="aside-title">Filter by {{object_list.form.brand.label_tag|striptags}}</h3>
        <ul class="list-links">
        {% for option in object_list.form.brand %}
            {{option}}
        {% endfor %}
        </ul>
    </div>
    <!-- /aside widget -->
    <!-- /aside widget -->
    <!-- aside widget -->
    <div class="aside">
        <h3 class="aside-title">Filter By Color:</h3>
        <ul class="color-option">
            <li><a href="#" style="background-color:#475984;"></a></li>
            <li><a href="#" style="background-color:#8A2454;"></a></li>
            <li class="active"><a href="#" style="background-color:#BF6989;"></a></li>
            <li><a href="#" style="background-color:#9A54D8;"></a></li>
            <li><a href="#" style="background-color:#675F52;"></a></li>
            <li><a href="#" style="background-color:#050505;"></a></li>
            <li><a href="#" style="background-color:#D5B47B;"></a></li>
            <li><a href="#" style="background-color:#475984;"></a></li>
            <li><a href="#" style="background-color:#8A2454;"></a></li>
            <li class="active"><a href="#" style="background-color:#BF6989;"></a></li>
            <li><a href="#" style="background-color:#9A54D8;"></a></li>
            <li><a href="#" style="background-color:#675F52;"></a></li>
            <li><a href="#" style="background-color:#050505;"></a></li>
            <li><a href="#" style="background-color:#D5B47B;"></a></li>
        </ul>
    </div>
    <!-- /aside widget -->
{% endif %}
{% top_rated  'Top Rated' %}
</div>
<!-- /ASIDE -->

products/templates/products/includes/base_js.html
	{% load static %}
    <!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	{% block extra_js %}{% endblock extra_js%}
	<script>
		$('.button').on('click', function(event){
			var type = $(this).data('type');
			var status = $(this).data('status');
			
			$('.button').removeClass('is-active');
			$(this).addClass('is-active');
			
			$('.notify')
				.removeClass()
				.attr('data-notification-status', status)
				.addClass(type + ' notify')
				.addClass('do-show'); 
			
			event.preventDefault();
		})
		$(".stars-rating").each(function(){
			const rating = $(this).data("rating");
			const numStars = $(this).data("numStars");
			const fullStar = '<i class="fa fa-star mr-2"></i>'.repeat(Math.floor(rating));
			const halfStar = (rating%1 !== 0) ? '<i class="fa fa-star-half-o mr-2"></i>': '';
			const noStar = '<i class="fa fa-star-o empty mr-2"></i>'.repeat(Math.floor(numStars - rating));
			$(this).html(`${fullStar}${halfStar}${noStar}`);
		})

		$('.filter-option').click(function(){	
			$('#filter-form').submit()		
		})
		$('select[name="sort_by"]').change(function(){
			$('#filter-form').submit()		
		})

		var billing_form  = $('.billing_form')
		var shipping_form = $('.shipping_form')
		var default_shipping = $('.default-shipping')
		var same_billing = $('.same-billing')
		var shipping_details = $('.shipping_details')

		var use_default_billing = document.querySelector('input[name=use_default_billing]')
		var use_default_shipping = document.querySelector('input[name=use_default_shipping]')
		var same_billing_address = document.querySelector('input[name=same_billing_address]')
		var set_default_billing = document.querySelector('input[name=set_default_billing]')

		use_default_billing.addEventListener('change', function(){
			if (this.checked){
				billing_form.hide();
			} else {
				billing_form.show();
			}
		})
		use_default_shipping.addEventListener('change', function(){
			if (this.checked){
				shipping_form.hide();
				same_billing.hide();
			} else {
				shipping_form.show();
				same_billing.show();
			}
		})
		same_billing_address.addEventListener('change', function(){
			if (this.checked){
				shipping_details.hide();
				default_shipping.hide();
			} else {
				shipping_details.show();
				default_shipping.show();
			}
		})


	
		
	</script>

products/templates/products/includes/body_header.html
{% load static %}
{% load cart_template_tags %}
{% load home_tags %}
<!-- HEADER -->
	<header>
		<!-- top Header -->
		<div id="top-header">
			<div class="container">
				<div class="pull-right">
					<ul class="header-top-links">
						<li><a href="{% url 'products:products-list'%}">Store</a></li>
						<li><a href="#">Newsletter</a></li>
						<li><a href="#">FAQ</a></li>
						<li class="dropdown default-dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">English (ENG)</a></li>
								<li><a href="#">Russian (Ru)</a></li>
								<li><a href="#">French (FR)</a></li>
								<li><a href="#">Spanish (Es)</a></li>
							</ul>
						</li>
						<li class="dropdown default-dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
							<ul class="custom-menu">
								<li><a href="#">USD ($)</a></li>
								<li><a href="#">NG (#)</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<!-- /top Header -->
		{% include "products/includes/messages.html" %}
		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href="{% url 'products:index' %}">
							<img src="{% static 'img/banny.png'%}" alt="">
						</a>
					</div>
					<!-- /Logo -->
					{% search_form request %}
				</div>
				<div class="pull-right">
					<ul class="header-btns">
                    {% if request.user.is_authenticated %}
						<!-- Account -->
						<li class="header-account dropdown default-dropdown">
							<div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
								<div class="header-btns-icon">
									<i class="fa fa-user-o"></i>
								</div>
								<strong class="text-uppercase">My Account <i class="fa fa-caret-down"></i></strong>
								<br>
								<span class="primary-color">{{ request.user.username }}</span>
							</div>
							
							<ul class="custom-menu">
								<li><a href="#"><i class="fa fa-user-o"></i> My Profile</a></li>
								<li><a href="#"><i class="fa fa-heart-o"></i> My Wishlist</a></li>
								<li><a href="#"><i class="fa fa-exchange"></i> Compare</a></li>
								{% comment %} <li><a href="#"><i class="fa fa-check"></i> Checkout</a></li> {% endcomment %}
								<li><a href="{% url 'account_logout' %}"><i class="fa fa-unlock-alt"></i> Logout</a></li>
							
							</ul>
						</li>
						<!-- /Account -->

						<!-- Cart -->
						<li class="header-cart dropdown default-dropdown">
							{% comment %} <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true"> {% endcomment %}
							<a href="{% url 'products:cart-summary'%}">
								<div class="header-btns-icon">
									<i class="fa fa-shopping-cart"></i>
									<span class="qty">{{ request.user|cart_item_count }}</span>
								</div>
								{% comment %}<span class="primary-color">${{ request.user|cart_total }}</span>
								 <br>
								<strong class="text-uppercase">Cart :</strong> {% endcomment %}
								
							</a>
							
						</li>
						<!-- /Cart -->
                        {% else %}
                        {% comment %} <li class="header-account" >
                                <div class="header-btns-icon">
									<i class="fa fa-sign-in"></i>
                                </div>
                                <a href= "{% url 'account_login' %}" class="text-uppercase">Login</a>
                        </li>
                        <li class="header-account" >
                            <a href="{% url 'account_signup' %}" class="text-uppercase">Sign Up</a>
                            <div class="header-btns-icon">
                                <i class="fa fa-user-plus"></i>
                            </div>
                        </li> {% endcomment %}
						<!-- Cart -->
						<li class="header-cart dropdown default-dropdown">
							{% comment %} <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true"> {% endcomment %}
							<a href="{% url 'products:cart-summary'%}">
								<div class="header-btns-icon">
									<i class="fa fa-shopping-cart"></i>
									<span class="qty">{{ request.session|anonymous_cart_item_count }}</span>
								</div>
								{% comment %}<span class="primary-color">${{ request.session|anonymous_cart_total }}</span>
								 <br>
								<strong class="text-uppercase">Cart</strong>							 {% endcomment %}
							</a>
							
						</li>
						<!-- /Cart -->
                        {% endif %}
						<!-- Mobile nav toggle-->
						<li class="nav-toggle pull-right">
							<button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
						</li>
						<!-- / Mobile nav toggle -->
					</ul>
				</div>
			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>
	<!-- /HEADER -->

products/templates/products/includes/cart.html
{% load static%}

<div class="section">
  <!-- container -->
  <div class="container">
    <div class="col-md-12">
      <div class="order-summary clearfix">
        <div class="section-title">
          <h3 class="title">Order Review</h3>
        </div>
        <table class="shopping-cart-table table">
          <thead>
            <tr>
              <th>Product</th>
              <th></th>
              <th class="text-center">Price</th>
              <th class="text-center">Quantity</th>
              <th class="text-center">Total</th>
              <th class="text-right"></th>
            </tr>
          </thead>
          <tbody>
          {% for order_item in object.items.all%}
            <tr>
              <td class="thumb"><img src="{{order_item.item.image.url}}" alt="" /></td>
              <td class="details">
                <a href="#">{{ order_item.item.title }}</a>
                <ul>
                  <li><span>Size: XL</span></li>
                  <li><span>Color: Camelot</span></li>
                </ul>
              </td>
              <td class="price text-center">
              {% if order_item.item.discount %}
                <strong>${{ order_item.item.discount }}</strong><br /><del class="font-weak"
                  ><small>${{ order_item.item.price }}</small></del
                >
                {% else %}
                <strong>${{ order_item.item.price }}</strong><br /><del class="font-weak"
                  >
                {% endif %}
              </td>
              <td class="qty text-center">
                <p class="qty"> 
                  <a href="{% url 'products:remove_single_item_from_cart' order_item.item.slug %}" class="btn btn-xs btn-sm primary-color">
                    <i class="fa fa-minus"></i>
                  </a> 
                  <span class="btn btn-xs btn-sm disabled"> {{ order_item.quantity }} </span>
                  <a href="{% url 'products:add_single_item_to_cart' order_item.item.slug %}" class="btn btn-xs primary-color">
                    <i class="fa fa-plus"></i>
                  </a> 
                </p>
              </td>
              <td class="total text-center">
              {% if order_item.item.discount %}
                <strong class="primary-color">${{ order_item.get_total_order_item_discount_price }}</strong>
              {% else %}
                <strong class="primary-color">${{ order_item.get_total_order_item_price }}</strong>
              {% endif %}
              </td>
              <td class="text-right">
                <a href="{% url 'products:remove-from-cart' order_item.item.slug %}" class="main-btn icon-btn">
                  <i class="fa fa-close"></i>
                </a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td class="price text-center" colspan="5"><p>Your cart is empty</p></td>
            </tr>
            <tr>
              <td colspan="5"> 
                <div class="price text-center">
                  <a href="{% url 'products:products-list' %}" class="primary-btn">Continue shopping</a>
                </div>
              </td>
            </tr>
            </tbody>
            </table>
            {% endfor %}
            {% if object.coupon.code %}
            <tr class="coupon-row">
              <td class="thumb"><img src="{% static 'img/banny.png'%}" alt="" /></td>
              <td class="total" colspan="3">
                <strong>{{ object.coupon.code }}</strong>
                <ul>
                  <li><span>{{ object.coupon.code }}</span></li>
                </ul>
              </td>
              <td class="total text-center">
                <strong class="coupon-amount">-${{ object.coupon.amount }}</strong>
              </td>
              <td class="text-right">
                <a href="{% url 'products:remove-coupon' %}" class="main-btn icon-btn">
                  <i class="fa fa-close"></i>
                </a>
              </td>
            </tr>
            {% endif %}
          </tbody>
          {% if object.get_total %}
          <tfoot>
            <tr>
              <th class="empty" colspan="3"></th>
              <th>SUBTOTAL</th>
              <th colspan="2" class="sub-total">${{ object.get_total }}</th>
            </tr>
            <tr>
              <th class="empty" colspan="3"></th>
              <th>SHIPPING</th>
              <td colspan="2">Free Shipping</td>
            </tr>
            <tr>
              <th class="empty" colspan="3"></th>
              <th>TOTAL</th>
              <th colspan="2" class="total">${{ object.get_total }}</th>
            </tr>
            {% if request.user.is_authenticated %}
            <tr>
              <th class="empty" colspan="3"></th>
              <th colspan="3">
              <form id="checkout-form" class="col-md-7 col-sm-12 col-xs-12" action="{% url 'products:add-coupon' %}" method="POST">
                {% csrf_token %}
                <div class="input-group">
                  {{couponform.code}}
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-success input-group-btn-store" id="button-addon1">Redeem</button>
                  </div>
                </div>
              </form>
              </th>
            </tr>
            {% endif %}
          </tfoot>
        </table>
        <div class="pull-right" style="padding-bottom:10px">
          <a href="{% url 'products:checkout' %}" class="primary-btn">Proceed to checkout</a>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
<div>

products/templates/products/includes/search_form.html
<!-- Search -->
<div class="header-search">
    <form action="{% url 'products:products-list' %}" method="GET">
    {{object_list.form.query}}
    {{object_list.form.category}}
        <button class="search-btn"><i class="fa fa-search"></i></button>
    </form>
</div>
<!-- /Search -->