cstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico',
         RedirectView.as_view(url='static/favicon.ico', permanent=False)),
    path('accounts/', include('allauth.urls')),
    path('', include('products.urls'), name='products'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from .views import (ProductDetailView, add_to_cart,
                    remove_from_cart, remove_single_item_from_cart,
                    IndexView, CollectionSearch, CartSummaryView,
                    CheckoutView, StripPaymentView, ProductList, 
                    FlutterwavePaymentView, AddCouponView, remove_coupon, show_category, CategoriesView)

app_name = 'products'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products/', ProductList.as_view(), name="products-list"),
    path('products/<slug:slug>/',
         ProductDetailView.as_view(),
         name="single-product"),
    path('summary/', CartSummaryView.as_view(), name="cart-summary"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('add-to-cart/<slug:slug>/', add_to_cart, name="add-to-cart"),
    path('add-coupon/', AddCouponView.as_view(), name="add-coupon"),
    path('remove-coupon/', remove_coupon, name="remove-coupon"),
    path('remove-from-cart/<slug:slug>/',
         remove_from_cart,
         name="remove-from-cart"),
    path('update-quantity-minus/<slug:slug>/',
         remove_single_item_from_cart,
         name="remove_single_item_from_cart"),
    path('update-quantity-plus/<slug:slug>/',
         add_to_cart,
         name="add_single_item_to_cart"),
    path('collections/<slug:slug>/', CollectionSearch.as_view(), name="collection"),
    path('categories/<slug:hierarchy>/', show_category, name="category"),
    path('categories/', CategoriesView.as_view(), name="categories"),
    path('payment/stripe/',
         StripPaymentView.as_view(),
         name="stripe"),
    path('payment/flutterwave/',
         FlutterwavePaymentView.as_view(),
         name="flutterwave"),

]

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save
from django.conf import settings
from django_countries.fields import CountryField
from cstore.utils import unique_slug_generator, store_url_slug_generator
import numpy as np
from django.contrib.auth import login
from django.contrib.auth.signals import user_logged_in
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import get_object_or_404
import uuid


class CategoryManager(models.Manager):
    # def get_queryset(self):
    #     return CollectionQueryset(self.model, using=self._db)

    def parent(self):
        return self.filter(parent=None)


class Category(models.Model):
    slug = models.SlugField(blank=True)
    title = models.CharField(max_length=50)
    show_in_homepage = models.BooleanField(default=False)
    parent = models.ForeignKey('self',
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True,
                               related_name='children')

    objects = CategoryManager()

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' > '.join(full_path[::-1])


class ProductImage(models.Model):
    item_instance = models.ForeignKey('Item', on_delete=models.CASCADE)
    large_image = models.ImageField(upload_to='images/large/',
                                    blank=True,
                                    null=True)
    thumb_image = models.ImageField(upload_to='images/thumb/',
                                    blank=True,
                                    null=True)

    def __str__(self):
        return self.item_instance.title


AVALIABILITY_CHOICES = (('1', 'IN STOCK'), ('0', 'OUT OF STOCK'))


class VarCategoryValues(models.Model):
    name = models.CharField(max_length=50)
    frontend_value = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(upload_to='images/variations/',
                              blank=True,
                              null=True)
    price = models.FloatField('Variation price', blank=True, null=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Variation(models.Model):
    name = models.CharField(max_length=50)
    values = models.ManyToManyField(VarCategoryValues)
    colors = models.BooleanField(
        help_text='click the checkbox if this is a color variation',
        default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    slug = models.SlugField(blank=True)
    title = models.CharField('Name', max_length=50)
    category = models.CharField(max_length=50)
    address = models.CharField(max_length=100, blank=False, null=False)
    logo = models.ImageField()
    website = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Item(models.Model):
    slug = models.SlugField(blank=True)
    title = models.CharField(max_length=100)
    brand = models.ForeignKey(Brand,
                              on_delete=models.CASCADE,
                              blank=True,
                              null=True)
    price = models.FloatField()
    discount = models.FloatField('Discount price', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    collections = models.ManyToManyField('Collection')
    description = models.TextField()
    avaliability = models.CharField(max_length=1,
                                    default='1',
                                    choices=AVALIABILITY_CHOICES)
    quantity_available = models.PositiveIntegerField()
    image = models.ImageField()
    variations = models.ManyToManyField(Variation, blank=True)

    def __str__(self):
        return self.title

    def get_cat_list(self):
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent
        for i in range(len(breadcrumb) - 1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i - 1:-1])
        return breadcrumb[-1:0:-1]

    def get_avg_rating(self):
        all_ratings = list(map(lambda x: x.rating, self.review_set.all()))
        l = len(all_ratings)
        if l == 0:
            return np.mean([0.5, 0.5])
        return np.mean(all_ratings)

    def get_absolute_url(self):
        return reverse("products:single-product", kwargs={"slug": self.slug})

    def get_add_to_cart_url(self):
        return reverse("products:add-to-cart", kwargs={"slug": self.slug})

    def get_remove_from_cart_url(self):
        return reverse("products:remove-from-cart", kwargs={"slug": self.slug})

    def get_percentage_discount(self):
        if self.discount:
            return round(((self.price - self.discount) / self.price) * 100)


class CollectionQueryset(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True)\
            .filter(featured_start_date_lt=timezone.now())\
            .filter(featured_end_date_gte=timezone.now())

    def add_to_carousel(self):
        return self.filter(add_to_carousel=True)


class CollectionManager(models.Manager):
    def get_queryset(self):
        return CollectionQueryset(self.model, using=self._db)

    def collections(self):
        return self.get_queryset().active().filter(add_to_carousel=False)

    def promos(self):
        return self.get_queryset().active().filter(is_promo=True)[:2]

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().active().featured()

    def carousels(self):
        return self.get_queryset().active().add_to_carousel()


TEXT_COLOR_CHOICES = (('primary-color', 'Theme-color'),
                      ('white-color', 'white-color'), ('black-color',
                                                       'black-color'))
POSITION_CHOICES = (('text-center', 'text-center'), ('left', 'left'))


class Collection(models.Model):
    slug = models.SlugField(blank=True)
    title = models.CharField(max_length=30)
    brand = models.ForeignKey(Brand,
                              on_delete=models.CASCADE,
                              blank=True,
                              null=True)
    header_text = models.CharField(max_length=100)
    header_text_color = models.CharField(max_length=20,
                                         default='primary-color',
                                         choices=TEXT_COLOR_CHOICES)
    brief_description = models.TextField(max_length=500)
    text_position = models.CharField(max_length=20,
                                     default='text-center',
                                     choices=POSITION_CHOICES)
    image = models.ImageField()
    large_image = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    featured_start_date = models.DateTimeField(auto_now=False,
                                               auto_now_add=False,
                                               blank=True,
                                               null=True)
    featured_end_date = models.DateTimeField(auto_now=False,
                                             auto_now_add=False,
                                             blank=True,
                                             null=True)
    active = models.BooleanField(default=False)
    add_to_carousel = models.BooleanField(default=False)
    is_promo = models.BooleanField(default=False)
    countdown_start_date = models.DateTimeField(auto_now=False,
                                                auto_now_add=False,
                                                blank=True,
                                                null=True)
    countdown_end_date = models.DateTimeField(auto_now=False,
                                              auto_now_add=False,
                                              blank=True,
                                              null=True)

    objects = CollectionManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("products:collection", kwargs={"slug": self.slug})


class Review(models.Model):
    RATING_CHOICES = ((1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'))
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=10)
    customer_email = models.CharField(max_length=50)
    comment = models.CharField(max_length=1000)
    rating = models.IntegerField(choices=RATING_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return "%s | %s" % (self.item.title, self.user_name)


class CartItemManager(models.Manager):
    def get_or_new(self, request, slug):
        cart_item_id = request.session.get("cart_item_id", None)
        item = get_object_or_404(Item, slug=slug)
        qs = self.get_queryset().filter(id=cart_item_id)
        if qs.exists():
            created = False
            cart_item = qs[0]
            if request.user.is_authenticated and cart_item.user is None:
                user = request.user
                cart_item.user = user
                cart_item.ordered = False
                cart_qs = Cart.objects.filter(user=user, ordered=False)
                if cart_qs.exists():
                    cart = cart_qs[0]

products/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (('S', 'Stripe'), ('F', 'Flutterwave'))


class CheckoutForm(forms.Form):
    shipping_street_address = forms.CharField(required=False)
    shipping_apartment_address = forms.CharField(required=False)
    shipping_country = CountryField(
        blank_label='--- Select country ---').formfield(
            required=False,
            widget=CountrySelectWidget(attrs={'class': 'input'}))
    shipping_zip_code = forms.CharField(required=False)

    billing_street_address = forms.CharField(required=False)
    billing_apartment_address = forms.CharField(required=False)
    billing_country = CountryField(
        blank_label='--- Select country ---').formfield(
            required=False,
            widget=CountrySelectWidget(attrs={'class': 'input'}))
    billing_zip_code = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect,
                                       choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'style': 'background-color:#fff',
            'placeholder': 'Coupon code',
            'aria-label': 'Coupon code',
            'aria-describedby': 'button-addon1'
        }))


class ReviewForm(forms.Form):
    user_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder': 'Your Name'
        }))
    customer_email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder': 'Email Address'
        }))
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'input',
        'placeholder': 'Comment'
    }))
    rating = forms.IntegerField(max_value=5)

products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
{% include "products/includes/head_links.html" %}
<body>

	{% include "products/includes/body_header.html" %}

	{% include "products/includes/nav.html" %}
    {% block content %}

    {% endblock content %}

	{% include 'products/includes/footer.html' %}
	{% block extra_script %}
		{% endblock extra_script %}

	{% include 'products/includes/base_js.html' %}
	

</body>

</html>

products/templates/products/base2.html
<!DOCTYPE html>
<html lang="en">
{% include "products/includes/head_links.html" %}
<body>

	{% include "products/includes/body_header.html" %}

	{% include "products/includes/nav.html" with css_class="show-on-click" %}

    {% block content %}

    {% endblock content %}

	{% include 'products/includes/footer.html' %}

	{% include 'products/includes/base_js.html' %}

</body>

</html>

products/templates/products/cart.html
{% extends 'products/base2.html' %}

{% block content %}

    {% include 'products/includes/cart.html' %}

{% endblock content %}

products/templates/products/item_filter.html
{% extends "products/base2.html" %}
{% load static %}


{% block content %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'products:index' %}">Home</a></li>
				<li><a href="#">Products</a></li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% include 'products/includes/aside-filters.html' %}
				<!-- MAIN -->
				<div id="main" class="col-md-9">
					<!-- store top filter -->
					{% include 'products/includes/storefilter.html' %}
					<!-- /store top filter -->
<form action="." method="GET">{{filter.form.as_p}}</form>
					<!-- STORE -->
					<div id="store">
						<!-- row -->
						<div class="row">
						{% for item in object_list %}
							<!-- Product Single -->
							<div class="col-md-4 col-sm-6 col-xs-6">
								<div class="product product-single">
									<div class="product-thumb">
										<div class="product-label">
											<span>New</span>
											{% if item.discount %}
											<span class="sale">-{{ item.get_percentage_discount }}%</span>
											{% endif %}
										</div>
										<a class="main-btn quick-view" href="{{ item.get_absolute_url }}"><i class="fa fa-search-plus"></i> View</a>
										<img src={{item.image.url}} width="270" height="360" alt="">
									</div>
									<div class="product-body">
									{% if item.discount %}
										<h3 class="product-price">${{ item.discount }} <del class="product-old-price">${{ item.price }}</del></h3>
									{% else %}
										<h3 class="product-price">${{ item.price }}</h3>
									{% endif %}
										<div class="product-rating stars-rating" data-rating="{{item.get_avg_rating}}" data-num-stars="5" alt="rated {{item.get_avg_rating}}"></div>
										<h2 class="product-name"><a href="{{ item.get_absolute_url }}">{{item.title}}</a></h2>
										<div class="product-btns">
											<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
											<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
											<a href="{{ item.get_add_to_cart_url }}" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
										</div>
									</div>
								</div>
							</div>
							<!-- /Product Single -->
						{% endfor %}


							<div class="clearfix visible-sm visible-xs"></div>

							<div class="clearfix visible-md visible-lg"></div>

						</div>
						<!-- /row -->
					</div>
					<!-- /STORE -->

					<!-- store bottom filter -->
					{% include 'products/includes/storefilter.html' %}
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	{% endblock content %}

	

products/templates/products/product-page.html
{% extends 'products/base2.html' %}
{% load static %}
{% load home_tags %}

{% block content %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'products:index' %}">Home</a></li>
				<li><a href="{% url 'products:products-list' %}">Products</a></li>
				{% for slug, name in breadcrumbs %}
				<li><a href="/category/{{slug}}">{{ name }}</a></li>
				{% endfor %}
				<li class="active">{{ object.title }}</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->



	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!--  Product Details -->
				<div class="product product-details clearfix">
					<div class="col-md-6">
						<div id="product-main-view">
						{% for i in item.productimage_set.all %}
							<div class="product-view">
								<img src="{{ i.large_image.url }}" alt="">
							</div>
						{% endfor %}
						</div>
						<div id="product-view">
						{% for i in item.productimage_set.all %}
							<div class="product-view">
								<img src="{{ i.thumb_image.url }}" alt="">
							</div>
						{% endfor %}
						</div>
					</div>
					<div class="col-md-6">
						<div class="product-body">
							<div class="product-label">
								<span>New</span>
								{% if item.discount %}
								<span class="sale">-{{ item.get_percentage_discount }}%</span>
								{% endif %}
							</div>
							<h2 class="product-name">{{ object.title }}</h2>
							{% if item.discount %}
								<h3 class="product-price">${{ item.discount }} <del class="product-old-price">${{ item.price }}</del></h3>
							{% else %}
								<h3 class="product-price">${{ item.price }}</h3>
							{% endif %}
							<div>
							    <div class="product-rating stars-rating" data-rating="{{item.get_avg_rating}}" data-num-stars="5" alt="rated {{item.get_avg_rating}}"></div>
								<a data-toggle="tab" href="#tab2">{{ item.review_set.count }} Review(s) / Add Review</a>
							</div>
							
							<p><strong>Availability:</strong> {{ item.get_avaliability_display }}</p>
							{% if item.brand %}<p><strong>Brand:</strong> {{ item.brand }}</p>{% endif %}
							<p>{{ object.description }}</p>
							{% if item.variations.all %}
							<div class="product-options">
							{% for category in item.variations.all %}
							{% if category.colors %}
								<ul class="color-option">
									<li><span class="text-uppercase">{{ category.name }}:</span></li>
									{% comment %} <li class="active"><a href="#" style="background-color:#475984;"></a></li> {% endcomment %}
									{% for value in category.values.all %}
									<li class="active"><a href="#" style="background-color:{{ value.frontend_value }}; border: 1px solid black"></a></li>
									{% endfor %}
								</ul>
							{% else %}					
								<ul class="size-option">
									<li><span class="text-uppercase">{{ category.name }}:</span></li>
									{% for value in category.values.all %}
									<li class="text-uppercase"><a href="#">{{ value.frontend_value }}</a></li>
									{% endfor %}
								</ul>
							{% endif %}
							{% endfor %}
							</div>
							{% endif %}

							<div class="product-btns">
								<div class="qty-input">
									<span class="text-uppercase">QTY: </span>
									<input class="input" type="number">
								</div>
								<a class="primary-btn add-to-cart" href="{{ object.get_add_to_cart_url }}"><i class="fa fa-shopping-cart"></i> Add to Cart</a>
								<div class="pull-right">
									<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-share-alt"></i></button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="product-tab">
							<ul class="tab-nav">
								<li class="active"><a data-toggle="tab" href="#tab1">Details</a></li>
								<li><a data-toggle="tab" href="#tab2">Reviews ({{ item.review_set.count }})</a></li>
							</ul>
							<div class="tab-content">
								<div id="tab1" class="tab-pane fade in active">
									<p>{{item.description}}</p>
								</div>
								<div id="tab2" class="tab-pane fade in">

									<div class="row">
										<div class="col-md-6">
											<div class="product-reviews">
											{% for review in reviews %}
												<div class="single-review">
													<div class="review-heading">
														<div><a href="#"><i class="fa fa-user-o"></i> {{review.user_name}}</a></div>
														<div><a href="#"><i class="fa fa-clock-o"></i> {{ review.created_at|date:'d M Y / H:i A' }}</a></div>
														<div 
														class="review-rating stars-rating pull-right" 
														data-rating="{{review.rating}}" 
														data-num-stars="5" 
														alt="rated {{review.rating}}"
														></div>
													</div>
													<div class="review-body">
														<p>{{review.comment}}</p>
													</div>
												</div>
											{% endfor %}

												<ul class="reviews-pages">
												{% if reviews.has_other_pages %}
												{% if reviews.has_previous %}
													<li><a href="?page={{reviews.previous_page_number}}"><i class="fa fa-caret-left"></i></a></li>
												{% else %}
													<li><i class="fa fa-caret-left"></i></li>
												{% endif %}
												{% for p in reviews.paginator.page_range %}
													{% if reviews.number == p %}
													<li class="active">{{p}}</li>
													{% elif p > reviews.number|add:'-3' and p < reviews.number|add:'3' %}
													<li><a href="?page={{p}}">{{p}}</a></li>
													{% endif %}
												{% endfor %}
												{% if reviews.has_next %}
													<li><a href="?page={{reviews.next_page_number}}"><i class="fa fa-caret-right"></i></a></li>
												{% else %}
													<li><i class="disabled fa fa-caret-right"></i></li>
												{% endif %}
												{% endif %}
												</ul>
											</div>
										</div>
										<div class="col-md-6">
											<h4 class="text-uppercase">Write Your Review</h4>
											<p>Your email address will not be published.</p>
											<form action="." method="POST" class="review-form">
											{% csrf_token %}
												<div class="form-group">
													{{form.user_name}}
												</div>
												<div class="form-group">
													{{form.customer_email}}
												</div>
												<div class="form-group">
													{{form.comment}}
												</div>
												<div class="form-group">
													<div class="input-rating">
														<strong class="text-uppercase">Rate this product: </strong>
														<div class="stars">
															<input type="radio" id="star5" name="rating" value="5" /><label for="star5"></label>
															<input type="radio" id="star4" name="rating" value="4" /><label for="star4"></label>
															<input type="radio" id="star3" name="rating" value="3" /><label for="star3"></label>
															<input type="radio" id="star2" name="rating" value="2" /><label for="star2"></label>
															<input type="radio" id="star1" name="rating" value="1" /><label for="star1"></label>
														</div>
													</div>
												</div>
												<button class="primary-btn">Submit</button>
											</form>
										</div>
									</div>



								</div>
							</div>
						</div>
					</div>

				</div>
				<!-- /Product Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			{% home_section related_products "Related Products" %}
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->
{% endblock content %}


{% block extra_js %}
	<script src={% static 'js/jquery.zoom.min.js' %}></script>
{% endblock extra_js%}

products/templates/products/search-results.html
{% extends "products/base2.html" %}


{% block content %}
	<!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="{% url 'products:index' %}">Home</a></li>
				<li><a href="#">Products</a></li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				{% include 'products/includes/aside-filters.html' %}

				<!-- MAIN -->
				<div id="main" class="col-md-9">
					<!-- store top filter -->
					{% include 'products/includes/storefilter.html' %}
					<!-- /store top filter -->

					<!-- STORE -->
					<div id="store">
						<!-- row -->
						
						<table class="shopping-cart-table table">
                            <tbody class="product">
                            {% for item in object_list.qs %}
                                <tr>
                                <div>
                                <td class="search-result-img">
                                    <div class="product-label" style="position:absolute" >
                                        <span style="color: rgb(160, 160, 160);background-color: #43444921;padding: 2px 5px">New</span>
                                        {% if item.discount %}
                                        <span class="sale" style="padding: 2px 5px">-{{ item.get_percentage_discount }}%</span>
                                        {% endif %}
                                    </div>
                                    <img style="width:100%;height:100%" src="{{item.image.url}}" alt="{{ item.title }}" />
                                </td>
                                <td class="details" style="padding-left:10px">
                                    <span class="font-weak">{{ item.brand.title }} | {{ item.category }}</span>
                                    <h3><a href="{{ item.get_absolute_url }}">{{ item.title|capfirst }}</a></h3>
                                    <h4>
                                    {% if item.discount %}
                                    <strong class="primary-color">${{ item.discount }}</strong><br /><del class="font-weak"
                                    ><small>${{ item.price }}</small></del
                                    >
                                    {% else %}
                                    <strong class="primary-color">${{ item.price }}</strong><br /><del class="font-weak"
                                    >
                                    {% endif %}
                                    </h4>
                                    <ul>
                                    <li><div class="product-rating stars-rating" data-rating="{{item.get_avg_rating}}" data-num-stars="5" alt="rated {{item.get_avg_rating}} of 5 stars"></div>
                                    </li></ul>                                
                                </td>
                                {% empty %}
                                <tr>
                                <td class="price text-center" colspan="5"><p>No Items</p></td>
                                </tr>
                                <tr>
                                <td colspan="5"> 
                                    <div class="price text-center">
                                    <a href="{% url 'products:products-list' %}" class="primary-btn">Continue shopping</a>
                                    </div>
                                </td>
                                </tr>
                                </tbody>
                                </table>
                                {% endfor %}
                            </tbody>
                            </table>


							<div class="clearfix visible-sm visible-xs"></div>

							<div class="clearfix visible-md visible-lg"></div>

						
						<!-- /row -->
					</div>
					<!-- /STORE -->

					<!-- store bottom filter -->
					{% include 'products/includes/storefilter.html' %}
					<!-- /store bottom filter -->
				</div>
				<!-- /MAIN -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	{% endblock content %}

	